### ISSUE TITLE
Ratchet 2

### ISSUE THREAD

**Issue by MichaelRelaxen** [MichaelRelaxen/racman#33]
npea00386

- [ ] infinite ammo
- [ ] fast loads
- [ ] save help
- [ ] yeedil act tuning
- [ ] snivelak act tuning
- [ ] gorn cutscene manip
- [ ] unlock items
- [ ] slots manip
- [ ] oozla/insomniac museum unlock

**Comment by elkoNDe** [comment]
> npea00386
> 
> * [x]  infinite ammo (kind of)
> * [x]  fast loads (kind of)
> * [x]  save help
> * [x]  yeedil act tuning
> * [x]  snivelak act tuning
> * [x]  gorn cutscene manip
> * [x]  unlock items
> * [ ]  slots manip
> * [x]  oozla/insomniac museum unlock
